<Project>
  <Import Project="$(MSBuildThisFileDirectory)Directory.Build.props.user"
          Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.props.user')" />

  <PropertyGroup>
    <SptRoot Condition="'$(SptRoot)' == '' and '$(SPT_ROOT)' != ''">$(SPT_ROOT)</SptRoot>
    <SptManaged>$(SptRoot)\EscapeFromTarkov_Data\Managed</SptManaged>
    <SptBepInEx>$(SptRoot)\BepInEx</SptBepInEx>
  </PropertyGroup>
</Project>
